apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: "splunk-flow-{{ .Chart.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  match:
    - select:
        labels:
          app: "{{ .Chart.Name }}"
          chart: "{{ .Chart.Name }}"
  localOutputRefs:
    - splunk-output