apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}"
  ports:
{{- if .Values.service }}
{{ toYaml .Values.service | indent 4 }}
{{- end }}
  type: NodePort
