import {MigrationInterface, QueryRunner} from "typeorm";

export class initial1609150553165 implements MigrationInterface {
    name = 'initial1609150553165'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "kitchen_groups" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255) NOT NULL, "ctx" number NOT NULL, CONSTRAINT "UQ_83c172e6a617728280097adf9d9" UNIQUE ("name"), CONSTRAINT "PK_d3020be6fed676449f10b6a0194" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kitchen_accounts" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255) NOT NULL, "fullName" varchar2(255) NOT NULL, "username" varchar2(255) NOT NULL, "mail" varchar2(255) NOT NULL, "mobile" varchar2(255) NOT NULL, "birthDate" varchar2(255) NOT NULL, "city" varchar2(255) NOT NULL, "title" varchar2(255) NOT NULL, "department" varchar2(255) NOT NULL, "division" varchar2(255) NOT NULL, "inDate" varchar2(255) NOT NULL, "vkID" varchar2(255) NOT NULL, "thumbnailPhoto" clob, CONSTRAINT "UQ_af24d99c119947a073000085a23" UNIQUE ("username"), CONSTRAINT "PK_9c4798d70cc7434e35094b2a55e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "domain" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "name" varchar2(255) NOT NULL, CONSTRAINT "UQ_26a07113f90df161f919c7d5a65" UNIQUE ("name"), CONSTRAINT "PK_27e3ec3ea0ae02c8c5bceab3ba9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "name" varchar2(255) NOT NULL, "domain_id" number, CONSTRAINT "UQ_8a45300fd825918f3b40195fbdc" UNIQUE ("name"), CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kuber" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "namespace" varchar2(255) NOT NULL, "domainId" number, CONSTRAINT "UQ_3276038c48582cf45f78e460016" UNIQUE ("namespace"), CONSTRAINT "PK_a909b5d83f19f3c30a4beaedce5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "network" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "base" varchar2(40) NOT NULL, "mask" varchar2(40) NOT NULL, "vos" number NOT NULL, "vlan" number NOT NULL, "description" varchar2(255), "domain_id" number, CONSTRAINT "UQ_41b984ad29aa94e71a53817acbd" UNIQUE ("base"), CONSTRAINT "PK_8f8264c2d37cbbd8282ee9a3c97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "host" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "ip" varchar2(40) NOT NULL, "dnsname" varchar2(255) NOT NULL, "os" varchar2(255) NOT NULL, "cpu" number NOT NULL, "ram" number NOT NULL, "hdd" number NOT NULL, "auth" varchar2(255) NOT NULL, "citrix" varchar2(255) NOT NULL, "description" varchar2(255), "network_id" number, CONSTRAINT "PK_44424c24c2f9b1d7bbf8721f4c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "application" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "name" varchar2(255) NOT NULL, "app_port" number NOT NULL, "netscaler_ip" varchar2(255) NOT NULL, "netscaler_url" varchar2(255) NOT NULL, "description" varchar2(255), "group_id" number, CONSTRAINT "PK_569e0c3e863ebdf5f2408ee1670" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kitchen_account_groups" ("account" number NOT NULL, "group" number NOT NULL, CONSTRAINT "PK_bb1073d75fcfa6e4257b327b98a" PRIMARY KEY ("account", "group"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59c8c49240d94295c3422c14ad" ON "kitchen_account_groups" ("account")`);
        await queryRunner.query(`CREATE INDEX "IDX_d3f7b55a0c0d2b594ec27b45f8" ON "kitchen_account_groups" ("group")`);
        await queryRunner.query(`CREATE TABLE "kuber_applications" ("kuber" number NOT NULL, "application" number NOT NULL, CONSTRAINT "PK_98fd03c9df863143ad0bcc32b5b" PRIMARY KEY ("kuber", "application"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b258f2bb07ffd287157eb87944" ON "kuber_applications" ("kuber")`);
        await queryRunner.query(`CREATE INDEX "IDX_cfab06af3238e485e7d1b03099" ON "kuber_applications" ("application")`);
        await queryRunner.query(`CREATE TABLE "host_applications" ("host" number NOT NULL, "application" number NOT NULL, CONSTRAINT "PK_6d1c6c1014b3e14938d0c508c23" PRIMARY KEY ("host", "application"))`);
        await queryRunner.query(`CREATE INDEX "IDX_83e7329236e65d96f8bc300280" ON "host_applications" ("host")`);
        await queryRunner.query(`CREATE INDEX "IDX_488265e3471045fde7c5a3b2ba" ON "host_applications" ("application")`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "FK_2c8a30e2e2d160c6f2d9a61eb7b" FOREIGN KEY ("domain_id") REFERENCES "domain" ("id")`);
        await queryRunner.query(`ALTER TABLE "kuber" ADD CONSTRAINT "FK_cb6fb982291eb9b8acc1a4da5ef" FOREIGN KEY ("domainId") REFERENCES "domain" ("id")`);
        await queryRunner.query(`ALTER TABLE "network" ADD CONSTRAINT "FK_4fd58a38acf673213737f9c0697" FOREIGN KEY ("domain_id") REFERENCES "domain" ("id")`);
        await queryRunner.query(`ALTER TABLE "host" ADD CONSTRAINT "FK_244fd7699d724928073f8b689f6" FOREIGN KEY ("network_id") REFERENCES "network" ("id")`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_6898c4ae79225be5023a8da3989" FOREIGN KEY ("group_id") REFERENCES "group" ("id")`);
        await queryRunner.query(`ALTER TABLE "kitchen_account_groups" ADD CONSTRAINT "FK_59c8c49240d94295c3422c14ade" FOREIGN KEY ("account") REFERENCES "kitchen_accounts" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "kitchen_account_groups" ADD CONSTRAINT "FK_d3f7b55a0c0d2b594ec27b45f87" FOREIGN KEY ("group") REFERENCES "kitchen_groups" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "kuber_applications" ADD CONSTRAINT "FK_b258f2bb07ffd287157eb879448" FOREIGN KEY ("kuber") REFERENCES "kuber" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "kuber_applications" ADD CONSTRAINT "FK_cfab06af3238e485e7d1b030999" FOREIGN KEY ("application") REFERENCES "application" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "host_applications" ADD CONSTRAINT "FK_83e7329236e65d96f8bc300280b" FOREIGN KEY ("host") REFERENCES "host" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "host_applications" ADD CONSTRAINT "FK_488265e3471045fde7c5a3b2ba5" FOREIGN KEY ("application") REFERENCES "application" ("id") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "host_applications" DROP CONSTRAINT "FK_488265e3471045fde7c5a3b2ba5"`);
        await queryRunner.query(`ALTER TABLE "host_applications" DROP CONSTRAINT "FK_83e7329236e65d96f8bc300280b"`);
        await queryRunner.query(`ALTER TABLE "kuber_applications" DROP CONSTRAINT "FK_cfab06af3238e485e7d1b030999"`);
        await queryRunner.query(`ALTER TABLE "kuber_applications" DROP CONSTRAINT "FK_b258f2bb07ffd287157eb879448"`);
        await queryRunner.query(`ALTER TABLE "kitchen_account_groups" DROP CONSTRAINT "FK_d3f7b55a0c0d2b594ec27b45f87"`);
        await queryRunner.query(`ALTER TABLE "kitchen_account_groups" DROP CONSTRAINT "FK_59c8c49240d94295c3422c14ade"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_6898c4ae79225be5023a8da3989"`);
        await queryRunner.query(`ALTER TABLE "host" DROP CONSTRAINT "FK_244fd7699d724928073f8b689f6"`);
        await queryRunner.query(`ALTER TABLE "network" DROP CONSTRAINT "FK_4fd58a38acf673213737f9c0697"`);
        await queryRunner.query(`ALTER TABLE "kuber" DROP CONSTRAINT "FK_cb6fb982291eb9b8acc1a4da5ef"`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "FK_2c8a30e2e2d160c6f2d9a61eb7b"`);
        await queryRunner.query(`DROP INDEX "IDX_488265e3471045fde7c5a3b2ba"`);
        await queryRunner.query(`DROP INDEX "IDX_83e7329236e65d96f8bc300280"`);
        await queryRunner.query(`DROP TABLE "host_applications"`);
        await queryRunner.query(`DROP INDEX "IDX_cfab06af3238e485e7d1b03099"`);
        await queryRunner.query(`DROP INDEX "IDX_b258f2bb07ffd287157eb87944"`);
        await queryRunner.query(`DROP TABLE "kuber_applications"`);
        await queryRunner.query(`DROP INDEX "IDX_d3f7b55a0c0d2b594ec27b45f8"`);
        await queryRunner.query(`DROP INDEX "IDX_59c8c49240d94295c3422c14ad"`);
        await queryRunner.query(`DROP TABLE "kitchen_account_groups"`);
        await queryRunner.query(`DROP TABLE "application"`);
        await queryRunner.query(`DROP TABLE "host"`);
        await queryRunner.query(`DROP TABLE "network"`);
        await queryRunner.query(`DROP TABLE "kuber"`);
        await queryRunner.query(`DROP TABLE "group"`);
        await queryRunner.query(`DROP TABLE "domain"`);
        await queryRunner.query(`DROP TABLE "kitchen_accounts"`);
        await queryRunner.query(`DROP TABLE "kitchen_groups"`);
    }

}
