import {MigrationInterface, QueryRunner} from "typeorm";

export class makeStructure1618830533864 implements MigrationInterface {
    name = 'makeStructure1618830533864'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "structure" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "json" nclob NOT NULL, CONSTRAINT "PK_90ac7986e769d602d218075215c" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "structure"`);
    }

}
