import {MigrationInterface, QueryRunner} from "typeorm";

export class certs1623355607241 implements MigrationInterface {
    name = 'certs1623355607241'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "cert-job" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "emails" varchar2(255) NOT NULL, "status" varchar2(255) NOT NULL, "cert_id" number, CONSTRAINT "PK_0c75cba38453e58a70997f3e0be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cert-file" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "name" varchar2(255) NOT NULL, "file" nclob NOT NULL, "status" varchar2(255) DEFAULT 'ACTIVE' NOT NULL, CONSTRAINT "PK_c358b24f17dc0a50fc6205f1c9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cert" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "validFrom" timestamp, "validTo" timestamp, "subject" varchar2(255) NOT NULL, "alertDate" timestamp, "certFileId" number, CONSTRAINT "PK_6a0ce80cc860598b4f16c00998c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "cert-job" ADD CONSTRAINT "FK_03f66ee4e94b9b257a8ff2f77c7" FOREIGN KEY ("cert_id") REFERENCES "cert" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cert" ADD CONSTRAINT "FK_1df82d9008ba7bbefba3f97c88b" FOREIGN KEY ("certFileId") REFERENCES "cert-file" ("id") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cert" DROP CONSTRAINT "FK_1df82d9008ba7bbefba3f97c88b"`);
        await queryRunner.query(`ALTER TABLE "cert-job" DROP CONSTRAINT "FK_03f66ee4e94b9b257a8ff2f77c7"`);
        await queryRunner.query(`DROP TABLE "cert"`);
        await queryRunner.query(`DROP TABLE "cert-file"`);
        await queryRunner.query(`DROP TABLE "cert-job"`);
    }

}
